# Generated by Django 3.2.13 on 2024-06-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20220619_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
