# Generated by Django 3.2.13 on 2024-06-27 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20240627_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='course_id',
            new_name='course',
        ),
    ]
