# Generated by Django 3.2.13 on 2024-06-27 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_rename_course_id_payment_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='course',
            new_name='course_id',
        ),
    ]
