# Generated by Django 3.2.13 on 2024-06-27 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20220618_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='contact',
            new_name='std_class',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='stream',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='student_number',
        ),
    ]
